### ISSUE TITLE
No workaround for `ValueAfterTable` ser errors

### ISSUE THREAD

**Issue by epage** [dtolnay/basic-toml#3]
e.g.
- toml-rs/toml#395
- toml-rs/toml#356
- toml-rs/toml-rs#407
- toml-rs/toml-rs#336
- toml-rs/toml-rs#286
- toml-rs/toml-rs#258
- toml-rs/toml-rs#145
- toml-rs/toml-rs#142

In the old `toml`, this is what [`toml::ser::tables_last`](https://docs.rs/toml/0.5.11/toml/ser/fn.tables_last.html) was for.  The only direct issue I see for this is toml-rs/toml-rs#458

**Comment by dtolnay** [comment]
Yep, I am not interested in supporting that. One would need to make sure the struct they are serializing has all its table-containing fields at the end.
